server:
  port: 8080
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    admin:
      auto-create: false
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # Jackson
      properties:
        # do not serialize the class name into the message
        "[spring.json.add.type.headers]": false
application:
  customers:
    initialization:
      enabled: ${CUSTOMERS_INITIALIZATION_ENABLED:false}
