application:
  customers:
    initialization:
      enabled: true
spring:
  datasource:
    url: jdbc:h2:./.local-db/data
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      path: /db
      enabled: true
  kafka:
    admin:
      auto-create: true
