server:
  port: 8080
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:h2:./.local-db/customers
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      path: /db
      enabled: true
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      # https://docs.spring.io/spring-kafka/reference/kafka/serdes.html#json-serde (Jackson)
      value-serializer: de.sample.schulung.accounts.kafka.CustomJsonSerializer
      properties:
        # do not serialize the class name into the message
        "[spring.json.add.type.headers]": false
application:
  customers:
    initialization:
      enabled: ${CUSTOMERS_INITIALIZATION_ENABLED:true}
  persistence:
    # if enabled, Transactional Outbos is possible
    enable-transactional-events: true